icecast:
    image: itsalexjones/icecast
    volumes:
    - logs:/var/log/icecast2
    - /etc/localtime:/etc/localtime:ro
    environment:
    - ICECAST_SOURCE_PASSWORD=aaa
    - ICECAST_ADMIN_PASSWORD=bbb
    - ICECAST_PASSWORD=ccc
    - ICECAST_RELAY_PASSWORD=ddd
    - ICECAST_HOSTNAME=noise.example.com
    - ICECAST_MAX_CLIENTS=1024
    - ICECAST_MAX_SOURCES=100
    - ICECAST_LOCATION=earth
    - ICECAST_ADMIN=admin@iceserver.com
    ports:
    - 8000:8000